### ISSUE TITLE
Is the command line broken?

### ISSUE THREAD

**Issue by trsh** [rust-lang-nursery/rust-bindgen#1310]
```
bindgen wrapper.h binding.rs RUST_BACKTRACE=1
thread 'main' panicked at 'TranslationUnit::parse failed', libcore/option.rs:917:5
```
1) No backtrace
2) The wrapper.h can be empty or contain some simple #include with simple header, it doesn't matter. It's same error.

```
bindgen --version
bindgen 0.36.1
```

Unix, Ubuntu

**Comment by nallar** [comment]
Try `RUST_BACKTRACE=1 bindgen wrapper.h binding.rs` to get the backtrace, don't think it will work at the end.

**Comment by trsh** [comment]
```
RUST_BACKTRACE=1 bindgen wrapper.h binding.rs
thread 'main' panicked at 'TranslationUnit::parse failed', libcore/option.rs:917:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::option::expect_failed
             at libcore/option.rs:917
  10: bindgen::ir::context::BindgenContext::new
  11: bindgen::Builder::generate
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  14: bindgen::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  19: main
  20: __libc_start_main
  21: _start

```

**Comment by trsh** [comment]
```
cargo install rustfmt
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing rustfmt v0.10.0                                                    
error: binary `cargo-fmt` already exists in destination
binary `rustfmt` already exists in destination
Add --force to overwrite
```

**Comment by nallar** [comment]
Try `rustup component add rustfmt-preview`

**Comment by trsh** [comment]
Thanks, now it worked!

**Comment by trsh** [comment]
Maybe, on rum. u can tell what im doing here wrong 

```
bindgen wrapper.h -o binding.rs --whitelist-type ns1__AddressValidationReply
wrapper.h:1:22: warning: extra tokens at end of #include directive [-Wextra-tokens], err: false
```

**Comment by trsh** [comment]
The struct is in the header file:

```
#ifndef SOAP_TYPE_ns1__AddressValidationReply
#define SOAP_TYPE_ns1__AddressValidationReply (20)
/* complex XSD type 'ns1:AddressValidationReply': */
struct ns1__AddressValidationReply {
        /** Required element 'ns1:HighestSeverity' of XSD type 'ns1:NotificationSeverityType' */
        enum ns1__NotificationSeverityType HighestSeverity;
        /** Sequence of at least 1 elements 'ns1:Notifications' of XSD type 'ns1:Notification' stored in dynamic array Notifications of length __sizeNotifications */
        int __sizeNotifications;
        struct ns1__Notification *Notifications;
        /** Optional element 'ns1:TransactionDetail' of XSD type 'ns1:TransactionDetail' */
        struct ns1__TransactionDetail *TransactionDetail;
        /** Required element 'ns1:Version' of XSD type 'ns1:VersionId' */
        struct ns1__VersionId *Version;
        /** Optional element 'ns1:ReplyTimestamp' of XSD type 'xsd:dateTime' */
        time_t *ReplyTimestamp;
        /** Sequence of elements 'ns1:AddressResults' of XSD type 'ns1:AddressValidationResult' stored in dynamic array AddressResults of length __sizeAddressResults */
        int __sizeAddressResults;
        struct ns1__AddressValidationResult *AddressResults;
};
#endif
```

But nothing is generated

**Comment by trsh** [comment]
Nevermind, some PC issue, locked files.
