### ISSUE TITLE
Panic when trying to compile "tinydx.h" from tinyrenderers

### ISSUE THREAD

**Issue by mattiascibien** [rust-lang-nursery/rust-bindgen#1319]
### Input C/C++ Header
https://github.com/mattiascibien/tinyrender/blob/master/native/tinydx.h from https://github.com/chaoticbob/tinyrenderers

### Bindgen Invocation
```Rust
    let bindings = bindgen::Builder::default()
        // The input header we would like to generate
        // bindings for.
        .clang_arg("-x c++")
        .header("native/tinydx.h")
        // Finish the builder and generate the bindings.
        .generate()
        // Unwrap the Result and panic on failure.
        .expect("Unable to generate bindings");
```

### Actual Results

```
error: failed to run custom build command for `tinyrender v0.1.0 (file:///C:/src/mine/tinyrender)`
process didn't exit successfully: `C:\src\mine\tinyrender\target\debug\build\tinyrender-d3ef1110b8985e3a\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'TranslationUnit::parse failed', libcore\option.rs:916:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:207
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:223
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:402
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:349
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:325
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:72
   9: core::option::expect_failed
             at C:\projects\rust\src\libcore\option.rs:916
  10: core::option::Option<bindgen::clang::TranslationUnit>::expect<bindgen::clang::TranslationUnit>
             at C:\projects\rust\src\libcore\option.rs:302
  11: bindgen::ir::context::BindgenContext::new
             at C:\Users\mattias.cibien\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.37.0\src\ir\context.rs:559
  12: bindgen::Bindings::generate
             at C:\Users\mattias.cibien\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.37.0\src\lib.rs:1634
  13: bindgen::Builder::generate
             at C:\Users\mattias.cibien\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.37.0\src\lib.rs:1102
  14: build_script_build::main
             at .\build.rs:9
  15: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  16: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  17: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:306
  18: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  19: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:285
  20: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:361
  21: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  22: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  23: main
  24: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  25: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  26: BaseThreadInitThunk
  27: RtlUserThreadStart
```

I am using clang 6.0.0 on windows (MSVC) with rust 1.26. Sample repo can be found at https://github.com/mattiascibien/tinyrender

**Comment by emilio** [comment]
That panic message happens when clang barfs at our input.

Are you sure the file has the right path? And have you tried to pass the clang flags separately:

```rust
clang_args(&["-x", "c++"])
```

I believe the last bit may be the root cause of the problem.

**Comment by mattiascibien** [comment]
I'll have a look. Thank you.

**Comment by mattiascibien** [comment]
with `clang_args(&["-x", "c++"])` it worked like a charm... Thank you.
